name: Upstream PR
on:
  push:
    branches: [ "cn" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

permissions:
  contents: write
  packages: read
  issues: write
  pull-requests: write

jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: emacs-ng/github-action-pull-upstream@master
      with:
        upstream: git@github.com:lcxfs1991/zh-hans.react.dev.git
        upstream_branch: main
        branch: cn
        pr_labels: upstream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: docschina2017@gmail.com
        DRY_RUN: false