name: Upstream PR
on:
  push:
    branches: [ "cn" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

jobs:  
  create-pull-request:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout upstream repository
        uses: actions/checkout@v4
        with:
          repository: git@github.com:reactjs/zh-hans.react.dev.git
          ref: main

      - name: Automatic rebase with upstream repository
        uses: marvinpinto/action-automatic-rebase@v1
        with:
          base: lcxfs1991/zh-hans.react.dev:cn
          fork: true

      - name: Create Pull Request to downstream repository
        uses: peter-evans/create-pull-request@v3
        with:
          title: Sync with upstream
          body: Automatic sync with upstream repository
          commit-message: Automatic sync with upstream repository
          labels: automatic-sync
          base: cn
          branch: sync-upstream
          token: ${{ secrets.GITHUB_TOKEN }}

