name: Upstream PR
on:
  push:
    branches: [ "cn" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

permissions:
  contents: write
  packages: read
  issues: write
  pull-requests: write

jobs:
  template-sync:
    name: Template Synchronise
    runs-on: ubuntu-latest
    # env:
    #   SYNCHRONISER_TOKEN: ${{ secrets.SYNCHRONISER_TOKEN || secrets.GITHUB_TOKEN } }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        # with:
        #   token: ${{ env.SYNCHRONISER_TOKEN }}

      - name: Render and synchronise the template repository
        uses: n3tuk/action-synchronise-upstream@v1
        with:
          # token: ${{ env.SYNCHRONISER_TOKEN }}
          repository: reactjs/zh-hans.react.dev
          branch: main
          target: cn
          labels: update from upstream